version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: userData
      MYSQL_ROOT_PASSWORD: Mysql@123
    ports:
      - '3306:3306'
  mailhog:
      image: mailhog/mailhog
      ports:
        - "1025:1025"
        - "8025:8025"